@startuml
actor 学生
participant 系统登陆
participant 标化考试成绩管理
participant 选校管理
participant 文书管理
participant 网申管理
participant 后期事务管理
学生->系统登陆: 用户名和密码
系统登陆-->学生: Token
学生->标化考试成绩管理: 考试类型及成绩
学生->选校管理: 欲申请学校
选校管理-->学生: 教师意见
选校管理->文书管理:选校列表
文书管理-->学生:文书信息
学生->文书管理:文书修改意见
选校管理->网申管理:选校列表
网申管理-->学生:各学校申请状态
网申管理->后期事务管理:已录取学校
后期事务管理-->学生:各事务截止日期
@enduml