@startuml
left to right direction
skinparam packageStyle rectangle
entity "StudentBasicInfo"  {
  * **id : int  <<PK>>**
  --
  first_name: string
  last_name: string
  phone: string
  address_line_1: string
  address_line_2: string
  sex: string
  ...
}

entity "SchoolInfo"{
  * **id : int  <<PK>>**
  --
  school_name: string
  url: string
  header: string
  body: string
}

entity "StudentSchool"{
  * **id : int  <<PK>>**
  --
  school_id: ** <<ref>> **
  student_id: ** <<ref>> **
}

StudentBasicInfo ||--|{ StudentSchool
SchoolInfo ||--|{ StudentSchool
@enduml