@startuml
actor 教师
participant 系统登陆
participant 标化考试成绩管理
participant 选校管理
participant 文书管理
participant 网申管理
participant 后期事务管理
教师->系统登陆: 用户名和密码
系统登陆-->教师: Token
教师->标化考试成绩管理: 学生id
标化考试成绩管理-->教师: 学生考试类型以及成绩
教师->选校管理: 学生id
选校管理-->教师:学生选校意向
教师->选校管理:教师意见
选校管理->文书管理:选校列表
教师->文书管理:上传文书
文书管理-->教师:学生修改内容
选校管理->网申管理:选校列表
教师->网申管理:各学校网申状态
网申管理->后期事务管理:已录取学校
教师->后期事务管理:各事项截止日期
@enduml