@startuml
left to right direction
skinparam packageStyle rectangle
actor 教师
actor 学生
rectangle 留学机构信息管理系统 {
  教师 -- (账户管理)
  (账户管理) .> (系统账户信息修改) : include
  (账户管理) .> (考试账户信息修改) : include
  (账户管理) -- 学生

  教师 -- (考试成绩管理)
  (考试成绩管理) .> (成绩录入) :include
  (考试成绩管理) .> (成绩查看) :include
  (考试成绩管理) .> (成绩删除) :include
  (考试成绩管理) -- 学生

  教师 -- (选校管理)
  (选校管理) .> (搜素学校) :include
  (选校管理) .> (添加待锁定项) :include
  (选校管理) .> (锁定项目) :include
  (解锁项目) .> (选校管理) :extend
  (选校管理) -- 学生


  教师 -- (文书管理)
  (文书管理) .> (查看历史版本文书) :include
  (查看历史版本文书) .> (下载文书) :include
  (文书管理) .> (新建文书) :include
  (新建文书) .> (添加备注) :include
  (文书管理) -- 学生

  教师 -- (申请管理)
  (申请管理) .> (查看申请状态) : include
  (修改申请状态) .> (申请管理) : extend
  (导入网申系统) .> (申请管理) : extend
  (申请管理) -- 学生

  教师 -- (作业管理)
  (作业管理) .> (查看历史作业) : include
  (添加作业) .> (作业管理) : extend

}
@enduml